public enum RequestType {
    LOGIN, ADD_PRODUCT, FIND_ALL_PRODUCTS, DELETE_PRODUCT, FIND_EMPLOYEE_BY_USERNAME, UPDATE_PRODUCT, FIND_ALL_ORDERS,
    FIND_BY_PRODUCT_ID, FIND_BY_ORDER_ID, UPDATE_ORDER, FIND_ALL_COMPANIES, ADD_ORDER, UPDATE_ORDER_STATUS;
}
